name: Build Geode Mod

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build for Platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main