name: Bug Report
description: report a bug 😮
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

  - type: textarea
    id: mods-list
    attributes:
      label: List of Mods
      description: go to geode settings then click copy mods list and paste it here
      placeholder: paste ALL of your mods list here not actually just my mod 🫩🙏
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: describe the issue with steps to reproduce it, especially if you have no screenshots or recordings. if possible, indicate if the bug happens with syzzi's cbf.
      placeholder: your mod is the best! 😁
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Media
      description: if possible, put any images or videos related to the bug here
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: pick the platform you saw the bug occurring
      options:
      - "Windows"
      - "Mac (Intel)"
      - "Mac (Arm)"
      - "Android (32-bit)"
      - "Android (64-bit)"
      - "iOS (JIT)"
      - "iOS (Jitless)"
      - "Linux"
    validations:
      required: true
      
  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      options:
      - label: I verify that Superb Input Precision is fully updated.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Come Back Later
        check back in a few days to see if i've responded to your report
        
